name: PR Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-check:
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deployment Check
        run: |
          if npm run build; then
            echo "Deployment check passed. Ready to merge."
          else
            echo "Deployment check failed. There are errors in the build."
            exit 1
          fi
